### ISSUE TITLE
Connect with Google-Account over Homey-Switchbot App returns "error 400: redirect_uri_mismatch"

### ISSUE THREAD

**Issue by dirkpollmann** [AdyRock/com.switchbot#117]
Request-id via Homey: b9c0ce5e-247f-43db-9984-ac3cff0aa50a

there is an issue when I trying to connect with my Switchbot account  via google Authentication:

> Access blocked: This app's request is invalid
> 
> ????@gmail.com
> You can't log in because this app sent an invalid request. Please try again later or contact the developer. More information about this error
> If you are a developer of this app, please see the bug details for more information.
> Error 400: redirect_uri_mismatch

additional message:

> You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 guidelines.

Links to Googles API documentation:

- https://developers.google.com/identity/protocols/oauth2/web-server?hl=de#authorization-errors-redirect-uri-mismatch

details: `redirect_uri=https://wondertechlabs.auth.us-east-1.amazoncognito.com/oauth2/idpresponse`

- https://developers.google.com/identity/protocols/oauth2/web-server?hl=de#authorization-errors-redirect-uri-mismatch

Hopefully, that can help to fixture that error.

best
Dirk

**Comment by AdyRock** [comment]
This is a known issue and I have contacted Switchbot to see if we can fix the problem. Unfortunately, I have no access to the servers required to fix it.

Currently the only solution is to create a new account with an email login and have your devices transferred.

**Comment by dirkpollmann** [comment]
Okay, thank you. that will work for me. Thank you

**Comment by marcelmarty** [comment]
@AdyRock I created a ticket for that issue on support@switchbot.com (Ticket #654531 -> "Google Auth not working since MONTHS (!!!)").

Latest information received from Switchbot:

_Good day!
 
We apologize for any inconvenience caused.
 
We also regret the difficulty you experienced in attempting to add a new device to your Homey system. Please be aware that our technical team is cognizant of this issue and has already begun working towards a resolution.
 
The techies have indicated that they are currently working with the community contributor responsible for the Homey side of the integration to try to resolve the issue.
 
Please be assured that we have made this issue a priority for us and the technical team will move forward with a resolution as soon as possible. Thank you for your patience and understanding. We will proactively let you know of any updates!
Thank you so much for your patience.
 
If you have any further questions or need assistance, please feel free to contact us.
Have a great day!🧡️
 
Best Regards,
Joyce
SwitchBot Customer Happiness
[www.switch-bot.com](http://www.switch-bot.com/)_

**Comment by AdyRock** [comment]
I have published a new test version that has an updated login system using the new servers.
Could you give that a try to see if it works for you?

**Comment by marcelmarty** [comment]
@AdyRock Seems to work at first glance. The login via Google works and the devices are added to Homey. I will test at lunchtime whether they can be switched on and off properly.

Many thanks for your valuable work.
