### ISSUE TITLE
Problem contact sensor a1

### ISSUE THREAD

**Issue by rudybom** [AdyRock/com.switchbot#14]
I managed to add the new contact sensor to homey but I am unable to use it. The motion sensor and contact sensor are working only once every ten times opening a door. When checking the switchbot app the contract sensor works normal but homey can't see it.

**Comment by AdyRock** [comment]
The problem is the polling interval. If the sensor is active and then inactive between polling then the API does return the action. 
Athom and I are trying to get Switchbot to implement Webhook notifications so the changes are sent immediately. Switchbot have not said no so hopefully it will come at some point. 
Personally I use my ESP32  module and it works well so if you can work out how to use that then I would recommend it.

**Comment by rudybom** [comment]
Hello, thanks for the reply. I understand that it is a problem from
switchbot and you and homey are waiting on them. In the mean time I don't
know anything about the module you are talking about even what it is ☹️ I
will wait for the possible update.


Op zo 14 nov. 2021 17:05 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
How technical are you?
It uses an ESP32 module available from places like Amazon at around £10.
You can then download the code from https://github.com/AdyRock/SwitchBotBLEHub and program it using the Arduino workbench. 
Instructions are in the readme in the repository. 
It takes a bit of effort but you will get instant responses from the Switchbot devices in Homey.

**Comment by rudybom** [comment]
I am a technician for the computers and payment terminals in patrol
stations, unfortunately I never learned to program. But I love to play with
home automation like the homey. I wanted to use the switchbot to automate
for example with the lights in the toilet, my kids always leave the lights
on. I already have stuff like when I open the window from a bedroom the
heater in that room shuts down till the window closes. I will try to read
the link you send in the weekend. Thanks

Op di 16 nov. 2021 20:42 schreef Adrian Rockall ***@***.***>:

**Comment by SortOfSmart** [comment]
Same issue here. I thought the polling interval was only a problem when using Hub mode, but since the contact sensors can only be added in Homey using BLE mode, I assume the mode doesn't matter? I can use the bots fine though Homey though; they may be a wee bit sluggish but they do respond every time. The sensors not so much.

I have the door sensors working through IFTTT, but that's a bit too slow for my taste. Contact sensors are great because they respond faster than motion sensors, but alas. The good news is that distinguishing between entering and exiting works as intended, even though Switchbot says that function is still in Beta. The Homey app doesn't have this function as far as I can see, but one would easily be able to work around this using flows. If they would report back in time, that is.

**Comment by AdyRock** [comment]
Unfortunately, Homey only updates the BLE data about every 20 to 30 seconds so that is the fastest response time. 
The difference is the BLE is a fixed rate regardless of the number of devices whereas the cloud is 20 seconds per device. So if you have 2 devices connected via the cloud then it will be 40 seconds  between updates  3 devices will be 60 seconds, etc.

**Comment by SortOfSmart** [comment]
I wish I'd done more research before investing in the mini hub and contact sensors. I'm a bit miffed, as I thought I'd get more use out of switchbot products with the hub. I've switched back to my 433 RF motion sensor for now, and I'm thinking of replacing all my contact sensors. I haven't been able to find a similar door/window sensor with motion sensor that actually works though (Philio has one, but it has it's own issues).

I don't really know what I'm talking about here, but would it be possible to bypass the response time in a similar way to importing scenes? Through Switchbot scenes, we can trigger something in the Switchbot ecosystem with all sorts of triggers outside of it. If the Switchbot app would have a virtual device and we could import this VD in Homey, we could do it the other way around: something in the Switchbot ecosystem could trigger anything outside of it. Does that make any kind of sense?

**Comment by AdyRock** [comment]
Sorry, I'm not sure what you mean.
I have no control over the SwitchBot end of things.

If you want to add any weight to my request with SwitchBot for webhooks then maybe you can vote in this issue https://github.com/OpenWonderLabs/SwitchBotAPI/issues/55

In theory, if they implement a webhook feature then Homey could be notified of changes straight away and the API would need to be polled at all.

**Comment by AdyRock** [comment]
If you are still using the SwitchBot contact sensor then the latest version of the app now supports the new webhook.
This means the detection of the contact is about 2 seconds, so it is now usable in flows, etc.
