### ISSUE TITLE
A/C control on Homey is not working

### ISSUE THREAD

**Issue by marcelmarty** [AdyRock/com.switchbot#33]
I made a simple A/C control with SwitchBot by recording the "on" and the "off" state of the A/C remote control.

Within the app on Android everything is working perfectly. Unfortunately, in the Homey App I'll get the following error "Command is not supported by SwitchBot" instead of sending the commands to the A/C.

![image](https://user-images.githubusercontent.com/1627210/178979062-19caf697-7716-4573-8e11-3398e8f5bb3d.png)

Did I make a mistake?

**Comment by marcelmarty** [comment]
Hi AdyRock

Thanks for reply. The logs have been sent successfully.

**Comment by AdyRock** [comment]
I have managed to recreate the problem, so now just need to find a way to fix it.
The issue is due to the normal AC interface requiring a combination of temperature, mode, fan speed and on / off. But as this is a DIY remote with only on and off, it is presumably not understanding the rest of the parameters. As none of that information is passed back from the hub I have no idea what features are supported by a DIY AC. I will do some digging to try and work it out.

**Comment by AdyRock** [comment]
OK, it appears the DIY AC only supports On and Off. So I have published a new Test version for you to try.

You will need to delete the existing AC from Homey and add it back in.

**Comment by marcelmarty** [comment]
Thank you very much. How can I test that? Do I have to install it manually, or by removing and adding the app again? What happens with my existing flows, if I remove the app and re-add it to Homey?

**Comment by marcelmarty** [comment]
Did try to install the app by this tutorial:
https://community.homey.app/t/how-to-cli-install-method/198

This seems to work:
![image](https://user-images.githubusercontent.com/1627210/179155430-37eadfeb-6ebd-4b98-a499-353ac1a4d8e3.png)

But after installation I always get the error message, that the app stopped unexpectedly. :-(

**Comment by marcelmarty** [comment]
Seems that this is the error:
![image](https://user-images.githubusercontent.com/1627210/179156387-14248896-0141-49ad-881a-29d2497f69c8.png)

**Comment by AdyRock** [comment]
You can install it from the Athom App Store. Find the app in the store and then add /test to the end of the URL of look at the change log and it will show Test for the latest version and click on that. You will then see a warning that it is a test version but just click on install.

Unfortunately, there are secret keys, supplied by SwitchBot, required for the authentication that I can't add to the repo, so that will cause error when trying to side load.

**Comment by marcelmarty** [comment]
In generally, it is working... But the buttons are reversed.. ;-) If I click in the SwitchBot app on the "on" button, then the A/C is starting correctly. If I do the same in Homey (clicking on "on"), then the A/C is turning off... Same if I click on "off" in the SwitchBox app, and clicking "on" on Homey...

Is that possible, or is that a misconfiguration by myself?

**Comment by AdyRock** [comment]
Oops, That was me having a silly moment. There is a new test version that fixes it.

**Comment by marcelmarty** [comment]
Works all like a charm.. Thank you very much...
