### ISSUE TITLE
adding device using Hub and Google

### ISSUE THREAD

**Issue by androbro** [AdyRock/com.switchbot#93]
Hi,
I have a switchbot bot and a hub mini.
When trying to add the hub bot i cannot login using Google or using the regular inputfields.

Yes i've reset my password and tripplechecked all my creds.

When using the google signin option (which i used to creat the app account) it throws an error 400: redirect_uri_mismatch.
With the title saying access blocked: access to this app is not valid.

How do i know this is a homey problem?
Well, i tried linking the switchbot app account to my google home account using google and that worked flawlessly whilst using the same login terminal as the homey one triggers.

Please check this out.

**Comment by AdyRock** [comment]
I'm not sure the Google login will work but I will check with my contact at Switchbot.

**Comment by chaosrain** [comment]
Same issue here. Screen caps in case they help to resolve. Might be an easy fix if the dialog is to be believed:

![Screenshot 2024-01-19 103756](https://github.com/AdyRock/com.switchbot/assets/18297664/5ed8b79a-128f-46db-9e02-630c8bbfd445)
![Screenshot 2024-01-19 103854](https://github.com/AdyRock/com.switchbot/assets/18297664/a52a07c9-ed98-4fa6-a6bc-3ad87d54ff99)

**Comment by androbro** [comment]
I found a possible solution by adding the dev api key from switchbot to the homey app. But... When i open the configure settings of the switchbot app on homey, it shows 3 tabs with a logging feature.

**Comment by AdyRock** [comment]
When Switchbot took over ownership of the app I switched to the OAUTH2 login that they provided and removed the API key method.

**Comment by androbro** [comment]
So bottom line is that there is no way to use homey with switchbot when ur account has been made using google? 😢

**Comment by AdyRock** [comment]
I started the app and had it working using the token obtained via the Switchbot phone app.
Athom then put me in touch with one of the founders of Switchbot to collaborate and make the login procedure 'easier' by using OAuth, at which time I transferred 'ownership' of the app to them, but I continued to do the development because they didn't want to take on the extra work. So as part of that Switchbot created OAuth keys for me to use in the app, but it only seems to work if you have created your account with an email address. I'm not sure if they can configure the AWS system to make the Google authentication work and they are not as responsive as they used to be, so I haven't got an answer to that.

**Comment by AdyRock** [comment]
Not sure if this will help you, but it's a workaround another user has found:
https://community.homey.app/t/app-cloud-pro-switchbot-release-1-1-35-test-1-1-38/42296/1009?u=adrian_rockall

**Comment by androbro** [comment]
I just asked switchbot to delete all my accounts and created a new one using email.

Works like a charm now.

Doesnt resolve the original issue though

**Comment by AdyRock** [comment]
Sorry, I'm confused. Is it working or still not allowing you to connect?

**Comment by androbro** [comment]
Nono its working fine now. Just needed to create an account on switchbot using anything else than google
